filebeat.inputs:
# Utiliser une configuration qui fonctionne sur Windows
- type: log
  enabled: true
  paths:
    - '/var/log/*.log'  # Chemin générique à l'intérieur du conteneur
  json.keys_under_root: true
  json.add_error_key: true

# Commentez la configuration Docker qui pose problème sur Windows
# processors:
#   - add_docker_metadata:
#       host: "unix:///var/run/docker.sock"
#   - decode_json_fields:
#       fields: ["message"]
#       target: "json"
#       overwrite_keys: true

# Ajoutez un processeur simplifié
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
setup.kibana:
  host: "kibana:5601"