global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8082']  # Changé de app à backend

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']