name: Auto Merge to Main

on:
  push:
    branches:
      - 'MedAmineAgoumi'
      - 'abdellah'
      - 'imad'
      - 'najd'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Auto merge to main
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}

          # Check if there are conflicts
          git fetch origin main
          if git merge-tree $(git merge-base FETCH_HEAD $CURRENT_BRANCH) FETCH_HEAD $CURRENT_BRANCH | grep -e "^<<<<<<<" -e "^>>>>>>>" -e "^=======$"; then
            echo "Conflicts detected, manual merge required"
            exit 0
          else
            # Create and auto-merge pull request if no conflicts
            gh pr create --base main --head $CURRENT_BRANCH --title "Auto-merge $CURRENT_BRANCH to main" --body "Automated merge from $CURRENT_BRANCH"
            gh pr merge --merge --auto
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
