name: Auto Merge to Main

on:
  push:
    branches:
      - 'MedAmineAgoumi'
      - 'abdellah'
      - 'imad'
      - 'najd'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MERGE_TOKEN }}
          
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Direct merge to main when no conflicts
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          echo "Current branch: $CURRENT_BRANCH"
          
          # Fetch the latest main branch
          git fetch origin main
          
          # Check if there are conflicts
          if git merge-tree $(git merge-base FETCH_HEAD $CURRENT_BRANCH) FETCH_HEAD $CURRENT_BRANCH | grep -e "^<<<<<<<" -e "^>>>>>>>" -e "^=======$"; then
            echo "Conflicts detected, manual merge required"
            exit 0
          else
            echo "No conflicts detected, proceeding with direct merge"
            
            # Checkout main branch
            git checkout main
            
            # Merge the feature branch
            git merge --no-ff $CURRENT_BRANCH -m "Auto-merge $CURRENT_BRANCH into main"
            
            # Push the changes to main
            git push origin main
            
            echo "Successfully merged $CURRENT_BRANCH into main"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}