name: Auto Merge to Main

on:
  push:
    branches:
      - 'MedAmineAgoumi'
      - 'abdellah'
      - 'imad'
      - 'najd'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Git and GitHub CLI
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Auto merge to main
        run: |
          CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          
          # Check if there are conflicts
          git fetch origin main
          if git merge-tree $(git merge-base FETCH_HEAD $CURRENT_BRANCH) FETCH_HEAD $CURRENT_BRANCH | grep -e "^<<<<<<<" -e "^>>>>>>>" -e "^=======$"; then
            echo "Conflicts detected, manual merge required"
            exit 0
          else
            # Check if PR already exists
            EXISTING_PR=$(gh pr list --head $CURRENT_BRANCH --base main --json number --jq '.[0].number')
            
            if [ -z "$EXISTING_PR" ]; then
              # Create new PR if none exists
              echo "Creating new PR for $CURRENT_BRANCH into main"
              gh pr create --base main --head $CURRENT_BRANCH --title "Auto-merge $CURRENT_BRANCH to main" --body "Automated merge from $CURRENT_BRANCH"
              PR_NUMBER=$(gh pr list --head $CURRENT_BRANCH --base main --json number --jq '.[0].number')
            else
              echo "PR #$EXISTING_PR already exists for $CURRENT_BRANCH into main"
              PR_NUMBER=$EXISTING_PR
            fi
            
            # Check PR status and merge if possible
            PR_STATUS=$(gh pr view $PR_NUMBER --json mergeable --jq '.mergeable')
            if [ "$PR_STATUS" == "true" ]; then
              echo "Merging PR #$PR_NUMBER"
              gh pr merge $PR_NUMBER --merge --auto
            else
              echo "PR #$PR_NUMBER is not in a mergeable state"
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
