name: Build and Push Docker Images

# This workflow runs when changes are pushed to main
on:
  push:
    branches:
      - 'main'
  # Optional: Allow manual triggering
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/projectmanagement-frontend:latest
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/projectmanagement-backend:latest
          
      - name: Image update notification
        run: |
          echo "Docker images have been successfully built and pushed to Docker Hub:"
          echo "- ${{ secrets.DOCKER_HUB_USERNAME }}/projectmanagement-frontend:latest"
          echo "- ${{ secrets.DOCKER_HUB_USERNAME }}/projectmanagement-backend:latest"