name: Java Tests and Coverage

on:
  push:
    branches: [ main, MedAmineAgoumi, abdellah, imad, najd ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests with coverage
      run: |
        cd backend
        mvn clean test jacoco:report
        
    - name: Generate JUnit Report
      uses: mikepenz/action-junit-report@v3
      if: always()  # Always run even if tests fail
      with:
        report_paths: 'backend/target/surefire-reports/TEST-*.xml'
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: backend/target/surefire-reports/
        
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/target/site/jacoco/
        
    - name: Coverage Report Summary
      run: |
        echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
        cd backend/target/site/jacoco/
        TOTAL_COVERAGE=$(grep -o 'Total[^%]*%' index.html | sed 's/<.*>//' | awk '{print $2}')
        echo "Overall coverage: $TOTAL_COVERAGE" >> $GITHUB_STEP_SUMMARY